[project]
name = "ha-mqtt-discoverable"
version = "1.0.0"
description = "Python library for creating MQTT entities compatible with Home Assistant"
readme = "README.md"
authors = [
    { name = "Joe Block", email = "jpb@unixorn.net" },
    { name = "Scott Hyndman", email = "scotty.hyndman@gmail.com" }
]
maintainers = [
    { name = "Scott Hyndman", email = "scotty.hyndman@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "gitlike-commands>=0.3.1",
    "aiomqtt>=2.5,<3",
    "pyaml>=26.2.1",
    "pydantic>=2.13.4",
    "structlog>=25.0",
]

[build-system]
requires = ["uv_build>=0.11.16,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "basedpyright>=1.39.6",
    "prek>=0.4.3",
    "pytest>=9.0.3",
    "pytest-mock>=3.15.1",
    "ruff>=0.15.15",
]

[tool.ruff]
target-version = "py313"
src = ["scripts", "src", "tests"]

[tool.basedpyright]
pythonVersion = "3.13"
typeCheckingMode = "recommended"
failOnWarnings = true
include = ["scripts", "src", "tests"]
extraPaths = ["src"]
reportUnusedCallResult = 'hint'

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]
