[project]
name = "ha-mqtt-discoverable"
version = "0.19.1"
description = "Python library for creating MQTT entities compatible with Home Assistant"
authors = [{name = "Joe Block", email = "jpb@unixorn.net"}]
readme = "README.md"
requires-python = ">=3.10.0,<4.0"
dependencies = [
    "pyaml==25.1.0",
    "paho-mqtt==2.1.0",
    "gitlike-commands (>=0.2.1,<0.4.0)",
    "pydantic==2.11.3",
]


[tool.poetry]
packages = [{include = "ha_mqtt_discoverable"}]


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
pre-commit = "^4.2.0"
ruff = "^0.11.7"


[tool.poetry.group.test.dependencies]
pytest-mock = "^3.10.0"


[build-system]
requires = ["poetry-core>=2.0"]
build-backend = "poetry.core.masonry.api"

